import { Suspense } from "react";
import { Inter } from "next/font/google";
import Header from "./Header";
import Footer from "./Footer";
import "./globals.css";
import type { Metadata } from "next";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEXT13-BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="conteiner mx-auto bg-slate-700 text-slate text-slate-50">
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
